"feature/deal/иницализировать коммит"
fancestyao/deal pull request #2
Opened 2023-08-17 15:42 UTC by fancestyao

2023-08-17 22:30 UTC, MrsIndianSummer requested changes

2023-08-17 22:48 UTC, MrsIndianSummer commented
![image](https://github.com/fancestyao/deal/assets/141334273/c8f90d5f-9ecb-43de-90fe-625351a44584)
Нужно добавить обработку ошибок от первого микросервиса

2023-08-17 22:59 UTC, MrsIndianSummer commented on src/main/java/study/neo/deal/services/classes/OfferServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Такой заявки не существует."));
стоит добавить в сообщение id запроса

2023-08-17 23:00 UTC, MrsIndianSummer commented on src/main/java/study/neo/deal/exceptions/ExceptHandler.java
> +        return new ErrorResponse(notFoundException.getMessage());
Было бы неплохо логировать сообщение

2023-08-18 07:42 UTC, fancestyao commented on src/main/java/study/neo/deal/entities/Application.java
У меня уже есть пакет с названием "models". Перенес туда сущности.

2023-08-18 07:42 UTC, fancestyao commented on src/main/java/study/neo/deal/models/Passport.java
Перенес Passport в пакет dtos.

2023-08-18 07:45 UTC, fancestyao commented on src/main/java/study/neo/deal/enums/ApplicationStatus.java
Исправил. Оставил только множественные числа в пакете "service", т.к. "class" и "interface" зарезервированы, не дает переименовать.

2023-08-18 07:48 UTC, fancestyao commented on src/main/java/study/neo/deal/entities/Credit.java
> +    private PaymentScheduleElement paymentSchedule;
Исправил.

2023-08-18 07:49 UTC, fancestyao commented on src/main/java/study/neo/deal/services/interfaces/ApplicationService.java
Действительно. Согласен. Исправил.

2023-08-18 08:34 UTC, fancestyao commented on src/main/java/study/neo/deal/services/classes/ApplicationServiceImpl.java
> +    public Application configureApplication(LoanApplicationRequestDTO loanApplicationRequestDTO) {
Добавил аннотацию Spring'а.

2023-08-21 06:14 UTC, fancestyao commented on src/main/java/study/neo/deal/services/classes/DealServiceImpl.java
> +    public List<LoanOfferDTO> application(LoanApplicationRequestDTO loanApplicationRequestDTO) {
Сделано.

2023-08-21 06:15 UTC, fancestyao commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
Сделано.

2023-08-21 06:29 UTC, fancestyao commented on src/main/java/study/neo/deal/dtos/LoanApplicationRequestDTO.java
> +    @Schema(description = "Дата рождения клиента (в формате yyyy-MM-dd)", example = "1999.05.18")
Исправил.

2023-08-21 06:47 UTC, fancestyao commented on src/main/java/study/neo/deal/services/interfaces/FeignConveyorClient.java
> +@FeignClient(name = "conveyor", url = "http://localhost:8080")
Готово.

2023-08-21 06:49 UTC, fancestyao commented on src/main/java/study/neo/deal/services/interfaces/FeignConveyorClient.java
> +    List<LoanOfferDTO> sendOffers(@RequestBody @Parameter(description =
Согласен. Исправил.

2023-08-21 06:50 UTC, fancestyao commented on src/main/java/study/neo/deal/services/interfaces/FeignConveyorClient.java
> +    List<LoanOfferDTO> sendOffers(@RequestBody @Parameter(description =
Использовал логику: "раз post-запрос, значит, отправляем, следовательно, send".

2023-08-21 06:54 UTC, fancestyao commented on src/main/java/study/neo/deal/services/classes/OfferServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Такой заявки не существует."));
В CalculateServiceImpl тоже исправил. Добавил айди и в лог, и в месседж эксепшена.

2023-08-25 17:57 UTC, merged